"""
CLI package re-exports.
This file simplifies importing the main command-line interface entry function.
"""

# CLI PACKAGE INTERFACE NOTES:
# -----------------------------
# This package exposes exactly one public symbol: `main` (the argparse-driven entry function).
# `python3 -m opencode_extractor.cli` is NOT handled here (no __main__.py in cli/), so the
# supported module invocation is `python3 -m opencode_extractor` (top-level __main__.py).
#
# The `main()` function handles argument parsing and command dispatching.
#
# AUTHORITATIVE CLI FLAG TABLE (registered in cli/main.py's argparse parser):
#   positional:
#       session_id    nargs="?"  default None   str   The target root session UUID, e.g. 'ses_12345'.
#                                                  Omitting it with no --all implies "just list sessions".
#   flags (all optional - argparse cannot error on a *missing* flag; only on unknown ones):
#       -h, --help    auto-generated by argparse. Prints usage + flags to stdout, then SystemExit(0).
#       --db          metavar DB, type str, default "all". Explicit .db path OR the literal 'all'
#                     to aggregate every discovered database. Value forms: "--db path", "--db=path",
#                     and ambiguous-abbreviation "--d" also works (allow_abbrev defaults True).
#       --out         metavar OUT, type str, default None. Destination directory. Folders are
#                     auto-created (mkdir parents=True). When omitted, nothing is written to disk.
#       --all         store_true, default False. Export every root session found.
#       --tool-calls  store_true, default False. Include tool-call transcripts. NOTE: inside main(),
#                     the exporter is always called with export_tool_calls=(args.tool_calls or True),
#                     i.e. this flag is effectively ALWAYS True and cannot turn transcripts OFF.
#       --zip         store_true, default False. Wrap the export in a .zip archive instead of a folder.
#       --list        store_true, default False. Print a session table and exit(0) before exporting.
#       --flat        store_true, default False. write files flat (no nested relative folders). Maps to
#                     preserve_paths=(not args.flat) when calling export_session_bundles.
#   FLAGS NOT REGISTERED (documented in docstrings but NOT in the parser, so they cause
#   "error: unrecognized arguments: <flag>", usage printed to stderr, SystemExit code 2):
#       --db-path, --output-dir, --format, --unexported-only, --gui
#
# ARGPARSE ERROR BEHAVIOR (what actually happens for bad input):
#   - Unknown flag:            prints "usage: ..." + "<prog>: error: unrecognized arguments: X" to STDERR,
#                              SystemExit(2).
#   - Missing required flags:  there are NO required flags; missing session_id is legal (nargs="?").
#   - Positional starting with '-': session IDs beginning with '-' are parsed as flags -> same error.
#   - Nothing to scan on disk: OpenCodeExtractor(db) raises FileNotFoundError (uncaught, traceback).
#   - Good/partial input:      exceptions raised during extraction (e.g. KeyError for a bad session_id
#                              from extract_session_bundle) propagate as tracebacks; no argparse error.
#
# RUNTIME BRANCH PRECEDENCE (main() checks, in order):
#   [args.list or (no session_id and no --all)] -> print table, sys.exit(0)
#   [args.all]                                  -> export all sessions  (session_id position is IGNORED)
#   [else]                                      -> export the single session_id (may be None; then a
#                                                 KeyError/None handling path effectively makes --all-less
#                                                 runs with a session print "Found 0 ..." summaries)
#
# BOUNDARY TESTING VALUES & VERIFICATION:
#   - Empty positional session_id list mode test: python3 -m opencode_extractor --list
#   - Invalid target folder permissions test: verifies clear permission error output when writing to read-only paths.
#   - No-args invocation: python3 -m opencode_extractor -> discovery printout + list table + exit 0.
#
# TESTING VALUES & EXTENSIONS:
#   - CLI Invocation: python3 -m opencode_extractor --list
#   - Tested File Types: .py, .sh, .bash, .js, .ts
from opencode_extractor.cli.main import main

# Expose the main function as the public interface for the CLI package.
__all__ = ["main"]